### PR TITLE
Parties list

### PR DESCRIPTION
**Pull request by AriHrannar**
Created a new tab for all political parties and getting them from the backend

### CODE REVIEW

**Comment by Ragnar-Hardarson** [comment]
Did you pull #22 into this PR?
There is some code that looks like it belongs there

**Comment by Ragnar-Hardarson** [comment]
It would also be nice to see some Stories with these components.
You can see how I made some [here](https://github.com/veritus/veritus-web/blob/master/src/Components/PoliticianCard/stories/PoliticianCard.stories.js)

**Comment by AriHrannar** [comment]
You will have to take me on a crash course for the stories :)

**Comment by AriHrannar** [comment]
Ive moved the website url to the dropdown instead of having it a a subtitle, it works better that way

**Comment by Ragnar-Hardarson** [comment]
> Did you pull #22 into this PR?
There is some code that looks like it belongs there

@AriHrannar could you clarify this for me?

**Comment by AriHrannar** [comment]
Yes I think i branched out from #22 and merged in create-promise aswell as i needed some code

**Comment by Ragnar-Hardarson** [comment]
All righty.

I'll update this branch and merge it into master then. This looks good as it is.
I'll take the liberty and update #31 from master once I'm done

**Pull request merged**
